# Generated by Django 5.2.1 on 2025-06-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_goal_created_at_goaldeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category'),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
