# Generated by Django 5.2.1 on 2025-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_bill_category_bill_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recently_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
